'use strict';

const PROJECTS = [
  {
    id: 'banking-pipeline',
    title: 'End-to-End Real-Time Banking Pipeline',
    tagline: 'OLTP → CDC → Warehouse → BI in a single production-grade stack',
    icon: '🏦',
    iconBg: 'rgba(249,115,22,0.12)',
    iconBorder: 'rgba(249,115,22,0.3)',
    accentColor: '#22c55e', accentRgb: '34,197,94',
    categories: ['engineering', 'realtime'],
    featured: true,
    badges: [
      { label: 'Real-time', color: 'orange' },
      { label: 'Enterprise', color: 'blue' },
    ],
    tech: ['PostgreSQL', 'Kafka', 'Debezium', 'Snowflake', 'dbt', 'Airflow', 'Power BI', 'Docker', 'CI/CD'],
    description: 'Production-mirrored banking data system — secure OLTP transactions flow through Debezium CDC into Kafka, land in Snowflake, are modeled with dbt, orchestrated by Airflow, and visualized in Power BI. End-to-end CI/CD included.',
    architecture: [
      { nodes: ['PostgreSQL\n(OLTP)'], color: 'green', arrow: true },
      { nodes: ['Debezium\nCDC'], color: 'orange', arrow: true },
      { nodes: ['Kafka'], color: 'orange', arrow: true },
      { nodes: ['Snowflake'], color: 'blue', arrow: true },
      { nodes: ['dbt'], color: 'teal', arrow: true },
      { nodes: ['Airflow'], color: 'purple', arrow: true },
      { nodes: ['Power BI'], color: 'yellow', arrow: false },
    ],
    highlights: [
      'Zero-downtime CDC with Debezium capturing row-level changes from PostgreSQL WAL',
      'Kafka topics partitioned by account type for parallel consumer throughput',
      'dbt staging → intermediate → mart layers with data contract tests',
      'Airflow DAGs with retry logic and SLA alerts via Slack webhook',
      'CI/CD pipeline: dbt test on PR, deploy to Snowflake prod on merge',
      'Power BI incremental refresh with DirectQuery mode for real-time tiles',
    ],
    githubUrl: '#',
    demoUrl: '#',
  },
  {
    id: 'logistics-platform',
    title: 'Logistics Analytics Platform',
    tagline: 'End-to-end operational analytics for warehouse & delivery monitoring',
    icon: '📦',
    iconBg: 'rgba(59,130,246,0.12)',
    iconBorder: 'rgba(59,130,246,0.3)',
    accentColor: '#93c5fd', accentRgb: '147,197,253',
    categories: ['engineering', 'analytics'],
    featured: false,
    badges: [
      { label: 'Analytics', color: 'purple' },
      { label: 'Ops', color: 'blue' },
    ],
    tech: ['Python', 'SQL', 'Airflow', 'dbt', 'DuckDB', 'HTML Dashboard', 'Docker'],
    description: 'Operational analytics system for a logistics network — tracks SLA breaches, hub performance, delivery success rates, and COD reconciliation. 5M+ synthetic shipments on DuckDB, orchestrated by Airflow, served via a static HTML dashboard (no Power BI needed).',
    architecture: [
      { nodes: ['Synthetic\nGenerator'], color: 'muted', arrow: true },
      { nodes: ['Raw\nParquet'], color: 'orange', arrow: true },
      { nodes: ['DuckDB'], color: 'teal', arrow: true },
      { nodes: ['dbt\nModels'], color: 'teal', arrow: true },
      { nodes: ['Airflow\nOrchestrate'], color: 'purple', arrow: true },
      { nodes: ['HTML\nDashboard'], color: 'yellow', arrow: false },
    ],
    highlights: [
      'Synthetic dataset modeled on Vietnamese 3PL ops — 5M shipments + 20M events with seasonality, geo skew, SLA breach patterns',
      'DuckDB as the analytical engine — 10x faster than SQLite for columnar queries on 5M+ rows',
      'dbt models: staging (raw cleanup) → core (fact/dim) → mart (business metrics)',
      'SLA breach detection with configurable thresholds per shipping zone, hub anomaly auto-flagging',
      'Daily Airflow DAG: generate → load → dbt run → quality gate → publish',
      'Static HTML dashboard — recruiter opens link directly, no Power BI Desktop required',
      'Dockerized stack — deployable on any VM with single docker-compose command',
    ],
    githubUrl: '#',
    demoUrl: '#',
  },
  {
    id: 'ai-analytics-assistant',
    title: 'AI Analytics Assistant',
    tagline: 'Live crypto data → streaming pipeline → ask in plain English → SQL → charts',
    icon: '🤖',
    iconBg: 'rgba(168,85,247,0.12)',
    iconBorder: 'rgba(168,85,247,0.3)',
    accentColor: '#c4b5fd', accentRgb: '196,181,253',
    categories: ['ai', 'analytics'],
    featured: true,
    badges: [
      { label: 'AI-Powered', color: 'purple' },
      { label: 'NL2SQL', color: 'teal' },
      { label: 'Streaming', color: 'blue' },
    ],
    tech: ['Python', 'Kafka', 'MinIO', 'PostgreSQL', 'Streamlit', 'Multi-LLM'],
    description: 'A real-time data platform: a crawler streams live crypto market data through Kafka into a MinIO data lake and a PostgreSQL warehouse, fed by always-on producer/consumer containers. On top sits a multi-LLM NL2SQL assistant — ask a question in plain English, it generates SQL, runs it read-only, and returns chart-ready results. Swap the LLM (Groq / Claude / Gemini / OpenAI / DeepSeek / Ollama) right from the UI.',
    architecture: [
      { nodes: ['CoinGecko\nAPI'], color: 'muted', arrow: true },
      { nodes: ['Kafka\nProducer'], color: 'orange', arrow: true },
      { nodes: ['Consumer'], color: 'teal', arrow: true },
      { nodes: ['MinIO +\nPostgres'], color: 'green', arrow: true },
      { nodes: ['Multi-LLM\nNL→SQL'], color: 'purple', arrow: true },
      { nodes: ['Streamlit\nDashboard'], color: 'blue', arrow: false },
    ],
    highlights: [
      'Real-time streaming ingest: CoinGecko → Kafka (KRaft) → consumer → MinIO data lake + Postgres warehouse, all running 24/7 in Docker',
      'Multi-LLM, switchable from the UI — Groq / Claude / Gemini / OpenAI / DeepSeek / Ollama via a provider registry + factory (one entry to add a vendor)',
      'Schema-aware prompting: injects live table DDL + sample rows + time-series hints so generated SQL handles "now" vs "over time"',
      'Two-layer SQL safety: a static guard rejects anything but a single SELECT, and queries run as a least-privilege read-only DB role',
      'Realtime analytics dashboard: auto-refreshing KPIs + market-cap / movers / price-trend / volume / sentiment charts',
      'Result auto-charting (time-series → line, ranking → bar) + one-click "Explain SQL" in plain language',
    ],
    githubUrl: 'https://github.com/ChanC003/ai-analytics-assistant',
    demoUrl: '#',
    screenshots: [
      { src: 'screenshots/ai-dashboard.png', caption: 'Realtime Market Dashboard — auto-refreshing KPIs + 5 analytics charts' },
      { src: 'screenshots/ai-ask.png',       caption: 'Ask the AI — plain English → SQL → chart + table (Download CSV / Explain SQL)' },
    ],
  },
  {
    id: 'data-governance',
    title: 'Data Governance & Quality Platform',
    tagline: 'Automated data contracts, lineage tracking, and quality monitoring across the warehouse',
    icon: '🛡️',
    iconBg: 'rgba(168,85,247,0.12)',
    iconBorder: 'rgba(168,85,247,0.3)',
    accentColor: '#c4b5fd', accentRgb: '196,181,253',
    categories: ['engineering', 'analytics', 'governance'],
    featured: false,
    badges: [
      { label: 'Governance', color: 'purple' },
      { label: 'Data Quality', color: 'blue' },
    ],
    tech: ['dbt', 'Great Expectations', 'Apache Atlas', 'Python', 'PostgreSQL', 'Airflow', 'Grafana'],
    description: 'End-to-end data governance platform enforcing data contracts, automated quality checks, column-level lineage, and PII classification — reducing downstream incidents from silent bad data.',
    architecture: [
      { nodes: ['Raw Sources'], color: 'muted', arrow: true },
      { nodes: ['Great Expectations'], color: 'orange', arrow: true },
      { nodes: ['dbt Contracts'], color: 'teal', arrow: true },
      { nodes: ['Apache Atlas'], color: 'purple', arrow: true },
      { nodes: ['Quality Dashboard'], color: 'blue', arrow: false },
    ],
    highlights: [
      'Data contracts enforced at ingestion: schema, nullability, value range, referential integrity',
      'Great Expectations suites auto-generated from dbt model metadata — zero manual config',
      'Column-level lineage tracked via Apache Atlas: source table → transformation → BI field',
      'PII scanner classifies sensitive columns (name, phone, email) and flags unmasked exposures',
      'Quality score per domain: freshness + completeness + validity aggregated into a single SLA metric',
      'Airflow DAG gates downstream pipelines — bad data quarantined before reaching the warehouse',
    ],
    githubUrl: '#',
    demoUrl: '#',
  },
  {
    id: 'hr-analytics-platform',
    title: 'HR Analytics Platform',
    tagline: 'People data → insight → action — workforce analytics from hire to exit',
    icon: '👥',
    iconBg: 'rgba(242,101,34,0.12)',
    iconBorder: 'rgba(242,101,34,0.3)',
    accentColor: '#F26522', accentRgb: '242,101,34',
    categories: ['engineering', 'analytics', 'ai'],
    featured: true,
    badges: [
      { label: 'ML + SHAP', color: 'orange' },
      { label: 'CI/CD', color: 'green' },
    ],
    tech: ['Python', 'PostgreSQL', 'MySQL', 'dbt', 'XGBoost', 'SHAP', 'Airflow', 'Docker', 'GitHub Actions'],
    description: 'End-to-end HR analytics platform on 10,000 synthetic employees — PostgreSQL OLTP → MySQL warehouse (incremental watermark load), dbt dimensional model (SCD2, 18 models / 53 tests), XGBoost attrition model with SHAP explainability + validated độ tin cậy (out-of-time/CV/baseline), GHN-style HTML dashboard, Airflow daily DAG with dbt-test quality gate, GitHub Actions CI + GitHub Pages live demo. 8/8 phase hoàn chỉnh.',
    architecture: [
      { nodes: ['Synthetic\nHR Data'], color: 'muted', arrow: true },
      { nodes: ['PostgreSQL\n(OLTP)'], color: 'green', arrow: true },
      { nodes: ['MySQL\n(Warehouse)'], color: 'blue', arrow: true },
      { nodes: ['dbt\nModels'], color: 'teal', arrow: true },
      { nodes: ['XGBoost\n+ SHAP'], color: 'purple', arrow: true },
      { nodes: ['Airflow\n+ CI/CD'], color: 'orange', arrow: true },
      { nodes: ['HTML\nDashboard'], color: 'yellow', arrow: false },
    ],
    highlights: [
      'Synthetic dataset: 10,000 employees × 3 years (seed cố định) — hire, quarterly reviews, salary changes, exits với tín hiệu nhân quả',
      'dbt SCD Type 2 dim_employee point-in-time correct — 18 models, 53 data-quality tests (gồm guard valid_to ≥ valid_from)',
      'XGBoost attrition classifier AUC-ROC 0.71 — đã validate: out-of-time 0.695, CV 0.718±0.007, baseline LogReg, calibration',
      'SHAP top-3 risk drivers per employee — "vì sao người này có thể nghỉ?" giải thích được cho HR',
      'GHN-style dashboard: 2 tab / 5 section, filter ăn khớp grain data, Phân tích + Khuyến nghị vận hành động theo bộ lọc',
      'Airflow DAG hr_daily_pipeline — dbt_test làm quality gate: data fail → pipeline dừng, không publish data lỗi',
      'GitHub Actions CI: ruff + pytest + JS test + chạy lại cả pipeline (generate→dbt→ML) mỗi push',
      'Deploy thật: CI cloud xanh mỗi push + dashboard public qua GitHub Pages — link demo sống mở trực tiếp trên trình duyệt',
    ],
    githubUrl: 'https://github.com/ChanC003/hr-analytics-platform',
    demoUrl: 'https://chanc003.github.io/hr-analytics-platform/',
  },
];
