'use strict';

const PROJECTS = [
  {
    id: 'banking-pipeline',
    title: 'End-to-End Real-Time Banking Pipeline',
    tagline: 'OLTP → CDC → Warehouse → BI in a single production-grade stack',
    icon: '🏦',
    iconBg: 'rgba(249,115,22,0.12)',
    iconBorder: 'rgba(249,115,22,0.3)',
    accentColor: '#22c55e', accentRgb: '34,197,94',
    categories: ['engineering', 'realtime'],
    featured: true,
    badges: [
      { label: 'Real-time', color: 'orange' },
      { label: 'Enterprise', color: 'blue' },
    ],
    tech: ['PostgreSQL', 'Kafka', 'Debezium', 'Snowflake', 'dbt', 'Airflow', 'Power BI', 'Docker', 'CI/CD'],
    description: 'Production-mirrored banking data system — secure OLTP transactions flow through Debezium CDC into Kafka, land in Snowflake, are modeled with dbt, orchestrated by Airflow, and visualized in Power BI. End-to-end CI/CD included.',
    architecture: [
      { nodes: ['PostgreSQL\n(OLTP)'], color: 'green', arrow: true },
      { nodes: ['Debezium\nCDC'], color: 'orange', arrow: true },
      { nodes: ['Kafka'], color: 'orange', arrow: true },
      { nodes: ['Snowflake'], color: 'blue', arrow: true },
      { nodes: ['dbt'], color: 'teal', arrow: true },
      { nodes: ['Airflow'], color: 'purple', arrow: true },
      { nodes: ['Power BI'], color: 'yellow', arrow: false },
    ],
    highlights: [
      'Zero-downtime CDC with Debezium capturing row-level changes from PostgreSQL WAL',
      'Kafka topics partitioned by account type for parallel consumer throughput',
      'dbt staging → intermediate → mart layers with data contract tests',
      'Airflow DAGs with retry logic and SLA alerts via Slack webhook',
      'CI/CD pipeline: dbt test on PR, deploy to Snowflake prod on merge',
      'Power BI incremental refresh with DirectQuery mode for real-time tiles',
    ],
    githubUrl: '#',
    demoUrl: '#',
  },
  {
    id: 'logistics-platform',
    title: 'Logistics Analytics Platform',
    tagline: '59M synthetic rows → DuckDB → dbt → Airflow → Metabase dashboards in one docker-compose',
    icon: '📦',
    iconBg: 'rgba(59,130,246,0.12)',
    iconBorder: 'rgba(59,130,246,0.3)',
    accentColor: '#93c5fd', accentRgb: '147,197,253',
    categories: ['engineering', 'analytics'],
    featured: true,
    badges: [
      { label: 'Analytics', color: 'purple' },
      { label: 'Metabase', color: 'blue' },
    ],
    tech: ['Python', 'DuckDB', 'dbt', 'Airflow', 'Metabase', 'Docker'],
    description: 'End-to-end logistics analytics platform — 59.4M synthetic rows (59M events across 11 tables) modeled on a Vietnamese 3PL network. Python generator → raw Parquet → DuckDB file warehouse → dbt 3-layer transform (88 tests PASS) → Airflow daily DAG 5/5 tasks → 4 Metabase dashboards (KPI, Hub Performance, SLA Analysis, COD Reconciliation). Full stack with one docker-compose up.',
    architecture: [
      { nodes: ['Python\nGenerator\n59M rows'], color: 'muted', arrow: true },
      { nodes: ['Raw\nParquet\n~2.7GB'], color: 'orange', arrow: true },
      { nodes: ['DuckDB\n5.1GB'], color: 'teal', arrow: true },
      { nodes: ['dbt\n27 models\n88 tests'], color: 'teal', arrow: true },
      { nodes: ['Airflow\n5/5 tasks\n~3min'], color: 'purple', arrow: true },
      { nodes: ['Metabase\n4 dashboards'], color: 'yellow', arrow: false },
    ],
    highlights: [
      '59.4M synthetic rows across 11 tables — Vietnamese 3PL patterns: seasonality (Tet/Nov-Dec peak), SLA breach 3-15%, dirty data at 1-16% with 3-tier severity',
      'DuckDB file-based warehouse (~5.1 GB) — star schema with 6 dims + 5 facts, vectorized columnar queries on 5M+ rows in seconds',
      'dbt 3-layer transform: staging (11 views, dedup/quarantine) → core (11 tables) → mart (5 pre-aggregated tables), 89 tests (88 PASS / 1 WARN by design)',
      'Airflow DAG logistics_daily: dbt_seed → dbt_run → dbt_test → dbt_snapshot → quality_check (5/5 PASS, ~3 min total)',
      'Metabase v0.52.9 + MotherDuck DuckDB driver (glibc custom Docker image) — 4 dashboards live at localhost:3000 with real data',
      'Data quality gate: Python assertions on 5 mart tables (row count + null key) — DAG fails if mart data corrupted',
      'Full stack single-command: docker-compose up spins airflow-db + airflow-init + webserver + scheduler + metabase',
    ],
    githubUrl: 'https://github.com/ChanC003/logistics-analytics-platform',
    demoUrl: '#',
  },
  {
    id: 'ai-analytics-assistant',
    title: 'AI Analytics Assistant',
    tagline: 'Live crypto data → streaming pipeline → ask in plain English → SQL → charts',
    icon: '🤖',
    iconBg: 'rgba(168,85,247,0.12)',
    iconBorder: 'rgba(168,85,247,0.3)',
    accentColor: '#c4b5fd', accentRgb: '196,181,253',
    categories: ['ai', 'analytics'],
    featured: true,
    badges: [
      { label: 'AI-Powered', color: 'purple' },
      { label: 'NL2SQL', color: 'teal' },
      { label: 'Streaming', color: 'blue' },
    ],
    tech: ['Python', 'Kafka', 'MinIO', 'PostgreSQL', 'Streamlit', 'Multi-LLM'],
    description: 'A real-time data platform: a crawler streams live crypto market data through Kafka into a MinIO data lake and a PostgreSQL warehouse, fed by always-on producer/consumer containers. On top sits a multi-LLM NL2SQL assistant — ask a question in plain English, it generates SQL, runs it read-only, and returns chart-ready results. Swap the LLM (Groq / Claude / Gemini / OpenAI / DeepSeek / Ollama) right from the UI.',
    architecture: [
      { nodes: ['CoinGecko\nAPI'], color: 'muted', arrow: true },
      { nodes: ['Kafka\nProducer'], color: 'orange', arrow: true },
      { nodes: ['Consumer'], color: 'teal', arrow: true },
      { nodes: ['MinIO +\nPostgres'], color: 'green', arrow: true },
      { nodes: ['Multi-LLM\nNL→SQL'], color: 'purple', arrow: true },
      { nodes: ['Streamlit\nDashboard'], color: 'blue', arrow: false },
    ],
    highlights: [
      'Real-time streaming ingest: CoinGecko → Kafka (KRaft) → consumer → MinIO data lake + Postgres warehouse, all running 24/7 in Docker',
      'Multi-LLM, switchable from the UI — Groq / Claude / Gemini / OpenAI / DeepSeek / Ollama via a provider registry + factory (one entry to add a vendor)',
      'Schema-aware prompting: injects live table DDL + sample rows + time-series hints so generated SQL handles "now" vs "over time"',
      'Two-layer SQL safety: a static guard rejects anything but a single SELECT, and queries run as a least-privilege read-only DB role',
      'Realtime analytics dashboard: auto-refreshing KPIs + market-cap / movers / price-trend / volume / sentiment charts',
      'Result auto-charting (time-series → line, ranking → bar) + one-click "Explain SQL" in plain language',
    ],
    githubUrl: 'https://github.com/ChanC003/ai-analytics-assistant',
    demoUrl: '#',
    screenshots: [
      { src: 'screenshots/ai-dashboard.png', caption: 'Realtime Market Dashboard — auto-refreshing KPIs + 5 analytics charts' },
      { src: 'screenshots/ai-ask.png',       caption: 'Ask the AI — plain English → SQL → chart + table (Download CSV / Explain SQL)' },
    ],
  },
  {
    id: 'hr-analytics-platform',
    title: 'HR Analytics Platform',
    tagline: 'People data → insight → action — workforce analytics from hire to exit',
    icon: '👥',
    iconBg: 'rgba(242,101,34,0.12)',
    iconBorder: 'rgba(242,101,34,0.3)',
    accentColor: '#F26522', accentRgb: '242,101,34',
    categories: ['engineering', 'analytics', 'ai'],
    featured: true,
    badges: [
      { label: 'ML + SHAP', color: 'orange' },
      { label: 'CI/CD', color: 'green' },
    ],
    tech: ['Python', 'PostgreSQL', 'MySQL', 'dbt', 'XGBoost', 'SHAP', 'Airflow', 'Docker', 'GitHub Actions'],
    description: 'End-to-end HR analytics platform on 10,000 synthetic employees — PostgreSQL OLTP → MySQL warehouse (incremental watermark load), dbt dimensional model (SCD2, 18 models / 53 tests), XGBoost attrition model with SHAP explainability + validated độ tin cậy (out-of-time/CV/baseline), GHN-style HTML dashboard, Airflow daily DAG with dbt-test quality gate, GitHub Actions CI + GitHub Pages live demo. 8/8 phase hoàn chỉnh.',
    architecture: [
      { nodes: ['Synthetic\nHR Data'], color: 'muted', arrow: true },
      { nodes: ['PostgreSQL\n(OLTP)'], color: 'green', arrow: true },
      { nodes: ['MySQL\n(Warehouse)'], color: 'blue', arrow: true },
      { nodes: ['dbt\nModels'], color: 'teal', arrow: true },
      { nodes: ['XGBoost\n+ SHAP'], color: 'purple', arrow: true },
      { nodes: ['Airflow\n+ CI/CD'], color: 'orange', arrow: true },
      { nodes: ['HTML\nDashboard'], color: 'yellow', arrow: false },
    ],
    highlights: [
      'Synthetic dataset: 10,000 employees × 3 years (seed cố định) — hire, quarterly reviews, salary changes, exits với tín hiệu nhân quả',
      'dbt SCD Type 2 dim_employee point-in-time correct — 18 models, 53 data-quality tests (gồm guard valid_to ≥ valid_from)',
      'XGBoost attrition classifier AUC-ROC 0.71 — đã validate: out-of-time 0.695, CV 0.718±0.007, baseline LogReg, calibration',
      'SHAP top-3 risk drivers per employee — "vì sao người này có thể nghỉ?" giải thích được cho HR',
      'GHN-style dashboard: 2 tab / 5 section, filter ăn khớp grain data, Phân tích + Khuyến nghị vận hành động theo bộ lọc',
      'Airflow DAG hr_daily_pipeline — dbt_test làm quality gate: data fail → pipeline dừng, không publish data lỗi',
      'GitHub Actions CI: ruff + pytest + JS test + chạy lại cả pipeline (generate→dbt→ML) mỗi push',
      'Deploy thật: CI cloud xanh mỗi push + dashboard public qua GitHub Pages — link demo sống mở trực tiếp trên trình duyệt',
    ],
    githubUrl: 'https://github.com/ChanC003/hr-analytics-platform',
    demoUrl: 'https://chanc003.github.io/hr-analytics-platform/',
  },
];
